# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/Configuring/Monitors/

monitor = , preferred, auto, 1


# If you need to scale things like steam etc, please uncomment these lines.
xwayland {
 force_zero_scaling = true       # Unscale XWayland
}

# Adjust GDK_SCALE accordingly to your liking.
#env = GDK_SCALE, 2                # GDK Scaling Factor (no fractional scaling)

# Electron based apps use X11 as default, auto should detect wayland
env = ELECTRON_OZONE_PLATFORM_HINT, auto

# Cambiar el escalado de la pantalla a 125%
# Para conseguir el nombre del monitor: "hyprctl monitors"
monitor = eDP-1, 2560x1440@60, 0x0, 1.25
monitor = eDP-2, 2560x1440@60, 0x0, 1.25

# Asegurarse que el escalado de monitores externos sea auto y mirror de la pantalla principal
monitor = HDMI-A-1,preferred, auto, 1, mirror, eDP-2
