# Binds para hacer capturas de pantalla
# 1. Region
bind =, Print, exec, sh -c 'REGION=$(slurp) || exit; grim -g "$REGION" - | wl-copy &&  wl-paste > ~/Pictures/screenshots/Screenshot-$(date +%F_%T).png && dunstify "Screenshot of the region taken" -t 1000'
# 2. Pantalla completa
bind = SHIFT, Print, exec, grim - | wl-copy && wl-paste > ~/Pictures/screenshots/Screenshot-$(date +%F_%T).png && dunstify "Screenshot of the whole screen taken" -t 1000

# Telling hyprland to run enirely in integrated gpu
env = AQ_DRM_DEVICES, /dev/dri/amd-igpu
